site_name: rtemis_a3

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            inherited_members: true
            show_source: false